# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20170610_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(blank=True, to='track.Genre'),
        ),
    ]
